version: '3'

services:
  webserver:
    image: nginx
    ports: 
      - 8080:80

  db:
    image: mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
  
  php:
    build:
      context: ./
    image: php-exozet/php-fpm
    container_name: php
    volumes: 
      - "./:/var/www/html/"